import { baseURL, initializeFetchUtil, makeHeaders, metadataValidatorsByType, validateApiData } from './api'
import { isApplication, isApplications } from './applications'
import { logError } from './errors'
import {
  createDirectory,
  createReadStream,
  createTemporaryDirectory,
  downloadFile,
  fileExists,
  getExtension,
  removeDirectory,
  saveFile,
} from './files'
import { prepareFormData, urlOrFile } from './forms'
import { isAudioExtension, isImageExtension, isVideoExtension } from './media'
import { isPaginated } from './pagination'
import { generatePath, withPaginationQueryParams, withQueryParams } from './paths'
import { exitProcess } from './process'
import { sanitizeHTML } from './sanitization'
import { uuid } from './strings'
import {
  assertType,
  isValidUrl,
  validatePresenceOf,
  validateURL,
  validateValueIsOfType,
  validateValueIsOfTypes,
  withValidation,
  withValidationAsync,
} from './validation'
import { validateLayerFormat } from './video'
import {
  formDataKey,
  processCompositionFile,
  validateAddAudio,
  validateAddFilter,
  validateAddHTML,
  validateAddImage,
  validateAddLottie,
  validateAddSubtitles,
  validateAddText,
  validateAddVideo,
  validateAddWaveform,
  validateCompositionFile,
  validateCompositionOptions,
  validateLayerMethod,
  validateVideoOptions,
} from './video/compositions'
import { validateFilter } from './video/filters'
import {
  validateFormat,
  validateHorizontalAlignment,
  validateLayerAlignment,
  validateLayerAudio,
  validateLayerBase,
  validateLayerFilter,
  validateLayerHTML,
  validateLayerLottie,
  validateLayerPositionableMedia,
  validateLayerSubtitles,
  validateLayerText,
  validateLayerTrim,
  validateLayerVisualMedia,
  validateTextAlignment,
  validateX,
  validateY,
} from './video/layers'
import { preparePreview } from './video/preview'
import {
  isApiAudioMetadata,
  isApiImageMetadata,
  isApiVideo,
  isApiVideoMetadata,
  isApiVideos,
  isEncodeResponse,
  validateNewVideo,
} from './videos'

export {
  assertType,
  baseURL,
  createDirectory,
  createReadStream,
  createTemporaryDirectory,
  downloadFile,
  exitProcess,
  fileExists,
  formDataKey,
  generatePath,
  getExtension,
  initializeFetchUtil,
  isApiAudioMetadata,
  isApiImageMetadata,
  isApiVideo,
  isApiVideoMetadata,
  isApiVideos,
  isApplication,
  isApplications,
  isAudioExtension,
  isEncodeResponse,
  isImageExtension,
  isPaginated,
  isValidUrl,
  isVideoExtension,
  logError,
  makeHeaders,
  metadataValidatorsByType,
  prepareFormData,
  preparePreview,
  processCompositionFile,
  removeDirectory,
  sanitizeHTML,
  saveFile,
  urlOrFile,
  uuid,
  validateAddAudio,
  validateAddFilter,
  validateAddHTML,
  validateAddImage,
  validateAddLottie,
  validateAddSubtitles,
  validateAddText,
  validateAddVideo,
  validateAddWaveform,
  validateApiData,
  validateCompositionFile,
  validateCompositionOptions,
  validateFilter,
  validateFormat,
  validateHorizontalAlignment,
  validateLayerAlignment,
  validateLayerAudio,
  validateLayerBase,
  validateLayerFilter,
  validateLayerHTML,
  validateLayerFormat,
  validateLayerLottie,
  validateLayerMethod,
  validateLayerPositionableMedia,
  validateLayerSubtitles,
  validateLayerText,
  validateLayerTrim,
  validateLayerVisualMedia,
  validateNewVideo,
  validatePresenceOf,
  validateTextAlignment,
  validateURL,
  validateValueIsOfType,
  validateValueIsOfTypes,
  validateVideoOptions,
  validateX,
  validateY,
  withPaginationQueryParams,
  withQueryParams,
  withValidation,
  withValidationAsync,
}
