export enum TextMethod {
  setBackgroundColor = 'setBackgroundColor',
  setBackgroundTransform = 'setBackgroundTransform',
  setBorder = 'setBorder',
  setBorderRadius = 'setBorderRadius',
  setColor = 'setColor',
  setFontFamily = 'setFontFamily',
  setFontSize = 'setFontSize',
  setFontStyle = 'setFontStyle',
  setFontWeight = 'setFontWeight',
  setLineHeight = 'setLineHeight',
  setPadding = 'setPadding',
  setText = 'setText',
  setTextAlign = 'setTextAlign',
  setTextDecoration = 'setTextDecoration',
  setTextPosition = 'setTextPosition',
  setTextTransform = 'setTextTransform',
}
